# Generated by Django 3.2.9 on 2022-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1600, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='base_page/image/Bio', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Біографія',
            },
        ),
        migrations.CreateModel(
            name='MyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Назва')),
                ('date', models.DateField(verbose_name='Дата')),
                ('image', models.ImageField(upload_to='base_page/image/MyPhoto', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Мої Фото',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Новини',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Назва')),
                ('date', models.DateField(verbose_name='Дата')),
                ('image', models.ImageField(upload_to='base_page/image/PhotoAlbum', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Альбом',
                'ordering': ['-date'],
            },
        ),
    ]
