# Generated by Django 3.2.9 on 2022-08-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Відео',
                'ordering': ['-date'],
            },
        ),
    ]
