# Generated by Django 3.2.9 on 2022-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.TextField(max_length=1500, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Назва'),
        ),
    ]
